CREATE TABLE sales (
	invoice_no text,
	sub_total real,
	sub_total_norm real,
	credit_total real,
	credit_total_norm real,
	tax_total real,
	tax_total_norm real,
	balance_due real,
	balance_due_norm real,
	clerk_id text,
	sold_to text,
	terms text,
	apply_con_bal real,
	invoice_total real,
	invoice_total_norm real,
	return_total real,
	return_total_norm real,
	sales_total_sub real,
	sales_total_sub_norm real,
	cash_returns_sub real,
	cash_returns_sub_norm real,
	credit_returns_sub real,
	credit_returns_sub_norm real,
	credit_returns_notax real,
	credit_returns_notax_norm real,
	the_date numeric,
	the_date_posix integer,
	discount_total real,
	discount_total_norm real,
	invoice_discount real,
	invoice_discount_norm real,
	credit_before real,
	credit_before_norm real,
	credit_after real,
	credit_after_norm real
);

